### Get Business

GET http://localhost:5000/api/v1/businesses/6a65d43d68426e84c94b2044
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTYzMjYxNjY5ZDEzYWFiZmU0ZDE3ZWQiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE2NWMwZDU2ODQyNmU4NGM5NGIyMDQzIiwiaWF0IjoxNzg1MDUzMzk3LCJleHAiOjE3ODUxMzk3OTcsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.DZ-TQABPyYFC3hMv94yXUrPDnXEW8F2HuX9nb1ds8rM

### List Businesses

GET http://localhost:5000/api/v1/businesses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTYzMjYxNjY5ZDEzYWFiZmU0ZDE3ZWQiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE2NWMwZDU2ODQyNmU4NGM5NGIyMDQzIiwiaWF0IjoxNzg1MDUzMzk3LCJleHAiOjE3ODUxMzk3OTcsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.DZ-TQABPyYFC3hMv94yXUrPDnXEW8F2HuX9nb1ds8rM

### Get Business Configuration

GET http://localhost:5000/api/v1/businesses/6a65d43d68426e84c94b2044/configuration
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTYzMjYxNjY5ZDEzYWFiZmU0ZDE3ZWQiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE2NWMwZDU2ODQyNmU4NGM5NGIyMDQzIiwiaWF0IjoxNzg1MDUzMzk3LCJleHAiOjE3ODUxMzk3OTcsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.DZ-TQABPyYFC3hMv94yXUrPDnXEW8F2HuX9nb1ds8rM