### Navigation - Get navigation (GET http://localhost:5000/api/v1/businesses/{{businessId}}/navigation)

GET http://localhost:5000/api/v1/businesses/6a6195da7d8e89d305b5756d/navigation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTVmNjk4YzI3NTY2OGM2YWIzYWM0MjQiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE2MGQwMmYyMDA5ZWE3YTQ5MmY5MTQ2IiwiaWF0IjoxNzg0NzI5NjQ3LCJleHAiOjE3ODQ4MTYwNDcsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.50bVYx-ZD9IPwESRSDQDrCRRBKG6tvBBRGao9S5w1T0

### Dashboard - Get Dashboard (GET http://localhost:5000/api/v1/businesses/{{businessId}}/dashboard)

GET http://localhost:5000/api/v1/businesses/6a69c08bef384dc38f9a5ad6/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTY4Nzc3Yzg2MTRjM2Y4Mzg3ZjVkYzgiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE2ODc3N2M4NjE0YzNmODM4N2Y1ZGM5IiwiaWF0IjoxNzg1MjMxMjI4LCJleHAiOjE3ODUzMTc2MjgsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.UFGTIQNVYqEhBzzhymJsRQ5HtiFW5T7vIH_45xWaXSQ

