### Navigation - Get navigation (GET http://localhost:5000/api/v1/businesses/{{businessId}}/navigation)

GET http://localhost:5000/api/v1/businesses/6a8fee64674abb8fc2b3ece1/navigation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YThkZGVlMzRjNjhhYzc0NWZkZTk3ZGMiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE4ZmIzYmM3ZjRkZDdhMGQ5MDk1YmJiIiwiaWF0IjoxNzg3ODAyNTU2LCJleHAiOjE3ODc4ODg5NTYsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.FWeILdbqILQlEmfcVKXFkCKcALt5P9PtGqW0602BxY8

### Dashboard - Get Dashboard (GET http://localhost:5000/api/v1/businesses/{{businessId}}/dashboard)

GET http://localhost:5000/api/v1/businesses/6a8fee64674abb8fc2b3ece1/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YThkZGVlMzRjNjhhYzc0NWZkZTk3ZGMiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE4ZmIzYmM3ZjRkZDdhMGQ5MDk1YmJiIiwiaWF0IjoxNzg3ODAyNTU2LCJleHAiOjE3ODc4ODg5NTYsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.FWeILdbqILQlEmfcVKXFkCKcALt5P9PtGqW0602BxY8

