### Create Offering

POST http://localhost:5000/api/v1/businesses/6a6c7a15c4217e5be0e7c210/offerings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTY4Nzc3Yzg2MTRjM2Y4Mzg3ZjVkYzgiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE2ZGRkNDk3YTY1NzM5ZjAxYWJmMzY4IiwiaWF0IjoxNzg1NTg0OTY5LCJleHAiOjE3ODU2NzEzNjksImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.T7AnOet6BZSnBlp_3dvL8QMfpvwj7RCxhW9-ONS7IF8
Content-Type: application/json

# {
#   "type": "PRODUCT",
#   "name": "Dell XPS 13",
#   "description": "13-inch developer laptop",
#   "visibility": "PUBLIC"
# }

# {
#     "type": "PRODUCT",
#     "name": "Dell XPS 15",
#     "shortDescription": "Developer Laptop",
#     "description": "Intel Core Ultra",
#     "sku": " dx15-001 ",
#     "categoryId": null
# }

{
    "type": "PRODUCT",
    "name": "Dell XPS 13",
    "shortDescription": "Developer Laptop",
    "description": "Intel Core Ultra",
    "sku": " dx13-001 ",
    "categoryId": null
}

# {
#     "type": "PRODUCT",
#     "name": "Dell XPS 17",
#     "sku": "DX15-001"
# }

# {
#   "type": "RENTAL",
#   "name": "Tsundere Hights",
#   "description": "Luxury hotels",
#   "visibility": "PUBLIC"
# }

# {
#     "type": "PRODUCT",
#     "name": "MacBook Pro M5",
#     "description": "Apple developer laptop",
#     "status": "DRAFT",
#     "visibility": "PUBLIC"
# }

### List Offerings

GET http://localhost:5000/api/v1/businesses/6a6c7a15c4217e5be0e7c210/offerings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTY4Nzc3Yzg2MTRjM2Y4Mzg3ZjVkYzgiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE2ZGRkNDk3YTY1NzM5ZjAxYWJmMzY4IiwiaWF0IjoxNzg1NTg0OTY5LCJleHAiOjE3ODU2NzEzNjksImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.T7AnOet6BZSnBlp_3dvL8QMfpvwj7RCxhW9-ONS7IF8

### Get Offering

GET http://localhost:5000/api/v1/businesses/6a6c7a15c4217e5be0e7c210/offerings/6a6dddf97a65739f01abf369
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTY4Nzc3Yzg2MTRjM2Y4Mzg3ZjVkYzgiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE2ZGRkNDk3YTY1NzM5ZjAxYWJmMzY4IiwiaWF0IjoxNzg1NTg0OTY5LCJleHAiOjE3ODU2NzEzNjksImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.T7AnOet6BZSnBlp_3dvL8QMfpvwj7RCxhW9-ONS7IF8

### Update Offering

PATCH http://localhost:5000/api/v1/businesses/6a6c7a15c4217e5be0e7c210/offerings/6a6ed01b520a6eb146c284d1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTY4Nzc3Yzg2MTRjM2Y4Mzg3ZjVkYzgiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE2ZGRkNDk3YTY1NzM5ZjAxYWJmMzY4IiwiaWF0IjoxNzg1NTg0OTY5LCJleHAiOjE3ODU2NzEzNjksImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.T7AnOet6BZSnBlp_3dvL8QMfpvwj7RCxhW9-ONS7IF8
Content-Type: application/json

# {
#   "name": "Dell XPS 13 Plus",
#   "description": "Updated description",
#   "visibility": "PRIVATE"
# }

# {
#     "name": "Dell XPS 15 Gen 2"
# }

{
    "sku": "DEV-200"
}

### Archive Offering

PATCH http://localhost:5000/api/v1/businesses/6a6c7a15c4217e5be0e7c210/offerings/6a6eccbf520a6eb146c284cc/archive
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTY4Nzc3Yzg2MTRjM2Y4Mzg3ZjVkYzgiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE2ZGRkNDk3YTY1NzM5ZjAxYWJmMzY4IiwiaWF0IjoxNzg1NTg0OTY5LCJleHAiOjE3ODU2NzEzNjksImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.T7AnOet6BZSnBlp_3dvL8QMfpvwj7RCxhW9-ONS7IF8

### Restore Offering

PATCH http://localhost:5000/api/v1/businesses/6a6c7a15c4217e5be0e7c210/offerings/6a6eccbf520a6eb146c284cc/restore
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTY4Nzc3Yzg2MTRjM2Y4Mzg3ZjVkYzgiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE2ZGRkNDk3YTY1NzM5ZjAxYWJmMzY4IiwiaWF0IjoxNzg1NTg0OTY5LCJleHAiOjE3ODU2NzEzNjksImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.T7AnOet6BZSnBlp_3dvL8QMfpvwj7RCxhW9-ONS7IF8

### Filter by type

GET http://localhost:5000/api/v1/businesses/6a6c7a15c4217e5be0e7c210/offerings?type=PRODUCT
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTY4Nzc3Yzg2MTRjM2Y4Mzg3ZjVkYzgiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE2Yzc5OTZjNDIxN2U1YmUwZTdjMjBmIiwiaWF0IjoxNzg1NDkzOTEwLCJleHAiOjE3ODU1ODAzMTAsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ia0C5c7He7iuXXSJPqZ7a15PxG1XF3sES6cIeRsK36I

### Filter by status

GET http://localhost:5000/api/v1/businesses/6a6c7a15c4217e5be0e7c210/offerings?status=ACTIVE
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTY4Nzc3Yzg2MTRjM2Y4Mzg3ZjVkYzgiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE2Yzc5OTZjNDIxN2U1YmUwZTdjMjBmIiwiaWF0IjoxNzg1NDkzOTEwLCJleHAiOjE3ODU1ODAzMTAsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ia0C5c7He7iuXXSJPqZ7a15PxG1XF3sES6cIeRsK36I

### Filter by visibility

GET http://localhost:5000/api/v1/businesses/6a6c7a15c4217e5be0e7c210/offerings?visibility=PUBLIC
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTY4Nzc3Yzg2MTRjM2Y4Mzg3ZjVkYzgiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE2Yzc5OTZjNDIxN2U1YmUwZTdjMjBmIiwiaWF0IjoxNzg1NDkzOTEwLCJleHAiOjE3ODU1ODAzMTAsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ia0C5c7He7iuXXSJPqZ7a15PxG1XF3sES6cIeRsK36I

### Search

GET http://localhost:5000/api/v1/businesses/6a6c7a15c4217e5be0e7c210/offerings?search=hotels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTY4Nzc3Yzg2MTRjM2Y4Mzg3ZjVkYzgiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE2ZGRkNDk3YTY1NzM5ZjAxYWJmMzY4IiwiaWF0IjoxNzg1NTg0OTY5LCJleHAiOjE3ODU2NzEzNjksImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.T7AnOet6BZSnBlp_3dvL8QMfpvwj7RCxhW9-ONS7IF8
