### Create a new product (POST http://localhost:5000/api/v1/businesses/:businessId/products)

POST http://localhost:5000/api/v1/businesses/6a567237b716e970fcb22872/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTU2NzE2YmI3MTZlOTcwZmNiMjI4NmYiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1NjcxZjBiNzE2ZTk3MGZjYjIyODcxIiwiaWF0IjoxNzg0MDUwMTYxLCJleHAiOjE3ODQxMzY1NjEsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.nBouUTAcgh800KSmXygq7pxULUhCFuL5UMlLSEx7HBU
Content-Type: application/json

{
  "name": "Dell XPS 13",
  "shortDescription": "Premium ultrabook",
  "description": "Intel Core Ultra, 16GB RAM, 512GB SSD",
  "sku": "DX13-001"
}

### List products (POST http://localhost:5000/api/v1/businesses/:businessId/products)

GET http://localhost:5000/api/v1/businesses/6a504c77e7296c01375cc578/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTRiOWQ4ODBiZTRkNDU1ZjRlNjhlNTAiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MDRiZDZlNzI5NmMwMTM3NWNjNTc3IiwiaWF0IjoxNzgzNjQ3MTkwLCJleHAiOjE3ODM3MzM1OTAsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ljIk-GFI1NZO5YAuZHYkLX56IHvjxAJbN5eNzOxqpSY
Content-Type: application/json

### get product data

GET http://localhost:5000/api/v1/businesses/6a504c77e7296c01375cc578/products/6a504e01e7296c01375cc57d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTRiOWQ4ODBiZTRkNDU1ZjRlNjhlNTAiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MDRiZDZlNzI5NmMwMTM3NWNjNTc3IiwiaWF0IjoxNzgzNjQ3MTkwLCJleHAiOjE3ODM3MzM1OTAsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ljIk-GFI1NZO5YAuZHYkLX56IHvjxAJbN5eNzOxqpSY
Content-Type: application/json

### Update product data

PATCH http://localhost:5000/api/v1/businesses/6a504c77e7296c01375cc578/products/6a504e01e7296c01375cc57d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTRiOWQ4ODBiZTRkNDU1ZjRlNjhlNTAiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MDRiZDZlNzI5NmMwMTM3NWNjNTc3IiwiaWF0IjoxNzgzNjQ3MTkwLCJleHAiOjE3ODM3MzM1OTAsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ljIk-GFI1NZO5YAuZHYkLX56IHvjxAJbN5eNzOxqpSY
Content-Type: application/json

{
  "name": "Dell XPS 13 Plus",
  "sku": "DX13-010"
}

### Delete product data

DELETE http://localhost:5000/api/v1/businesses/6a504c77e7296c01375cc578/products/6a504e01e7296c01375cc57d/restore
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTRiOWQ4ODBiZTRkNDU1ZjRlNjhlNTAiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MDRiZDZlNzI5NmMwMTM3NWNjNTc3IiwiaWF0IjoxNzgzNjQ3MTkwLCJleHAiOjE3ODM3MzM1OTAsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ljIk-GFI1NZO5YAuZHYkLX56IHvjxAJbN5eNzOxqpSY
Content-Type: application/json

### Delete product data

PATCH http://localhost:5000/api/v1/businesses/6a504c77e7296c01375cc578/products/6a504e01e7296c01375cc57d/restore
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTRiOWQ4ODBiZTRkNDU1ZjRlNjhlNTAiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MDRiZDZlNzI5NmMwMTM3NWNjNTc3IiwiaWF0IjoxNzgzNjQ3MTkwLCJleHAiOjE3ODM3MzM1OTAsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ljIk-GFI1NZO5YAuZHYkLX56IHvjxAJbN5eNzOxqpSY
Content-Type: application/json

### Category - create (POST http://localhost:5000/api/v1/businesses/:businessId/categories, {"name": "Electronics", "description": "Electronic devices and accessories"})

POST http://localhost:5000/api/v1/businesses/6a50f1ce20478765e4be70fa/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUwZjE4OTIwNDc4NzY1ZTRiZTcwZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MGYxOTUyMDQ3ODc2NWU0YmU3MGY5IiwiaWF0IjoxNzgzNjg5NjIxLCJleHAiOjE3ODM3NzYwMjEsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.081fWblecul08_H5Gm3NsYqz9K6asRSRIwd5OVszYbw
Content-Type: application/json

# {
# 	"name": "Electronics",
# 	"description": "Electronic devices and accessories"
# }

# Create Child Category ({"name": "Laptops", "parentCategoryId": "<electronicsId>"})

{
	"name": "Laptops",
	"parentCategoryId": "6a5106dea0f00edab39a3f0d"
}

### Category - read (GET http://localhost:5000/api/v1/businesses/:businessId/categories)

GET http://localhost:5000/api/v1/businesses/6a50f1ce20478765e4be70fa/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUwZjE4OTIwNDc4NzY1ZTRiZTcwZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MGYxOTUyMDQ3ODc2NWU0YmU3MGY5IiwiaWF0IjoxNzgzNjg5NjIxLCJleHAiOjE3ODM3NzYwMjEsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.081fWblecul08_H5Gm3NsYqz9K6asRSRIwd5OVszYbw
Content-Type: application/json

### Category - read 1 (GET http://localhost:5000/api/v1/businesses/:businessId/categories/:categoryId)

GET http://localhost:5000/api/v1/businesses/6a50f1ce20478765e4be70fa/categories/6a510919a0f00edab39a3f0f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUwZjE4OTIwNDc4NzY1ZTRiZTcwZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MGYxOTUyMDQ3ODc2NWU0YmU3MGY5IiwiaWF0IjoxNzgzNjg5NjIxLCJleHAiOjE3ODM3NzYwMjEsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.081fWblecul08_H5Gm3NsYqz9K6asRSRIwd5OVszYbw
Content-Type: application/json

### Category - update (PATCH http://localhost:5000/api/v1/businesses/:businessId/categories/:categoryId, {"name": "Computer Hardware", "description": "Updated description"})

PATCH http://localhost:5000/api/v1/businesses/6a50f1ce20478765e4be70fa/categories/6a5106dea0f00edab39a3f0d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUwZjE4OTIwNDc4NzY1ZTRiZTcwZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MGYxOTUyMDQ3ODc2NWU0YmU3MGY5IiwiaWF0IjoxNzgzNjg5NjIxLCJleHAiOjE3ODM3NzYwMjEsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.081fWblecul08_H5Gm3NsYqz9K6asRSRIwd5OVszYbw
Content-Type: application/json

{
	"parentCategoryId": "6a510919a0f00edab39a3f0f"
}

### Category - delete

DELETE http://localhost:5000/api/v1/businesses/6a50f1ce20478765e4be70fa/categories/6a510919a0f00edab39a3f0f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUwZjE4OTIwNDc4NzY1ZTRiZTcwZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MGYxOTUyMDQ3ODc2NWU0YmU3MGY5IiwiaWF0IjoxNzgzNjg5NjIxLCJleHAiOjE3ODM3NzYwMjEsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.081fWblecul08_H5Gm3NsYqz9K6asRSRIwd5OVszYbw
Content-Type: application/json

### Category - restore

PATCH http://localhost:5000/api/v1/businesses/6a50f1ce20478765e4be70fa/categories/6a510919a0f00edab39a3f0f/restore
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUwZjE4OTIwNDc4NzY1ZTRiZTcwZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MGYxOTUyMDQ3ODc2NWU0YmU3MGY5IiwiaWF0IjoxNzgzNjg5NjIxLCJleHAiOjE3ODM3NzYwMjEsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.081fWblecul08_H5Gm3NsYqz9K6asRSRIwd5OVszYbw
Content-Type: application/json

### Category - Parent Validation, Self Parent Validation

POST http://localhost:5000/api/v1/businesses/6a50f1ce20478765e4be70fa/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUwZjE4OTIwNDc4NzY1ZTRiZTcwZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MGYxOTUyMDQ3ODc2NWU0YmU3MGY5IiwiaWF0IjoxNzgzNjg5NjIxLCJleHAiOjE3ODM3NzYwMjEsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.081fWblecul08_H5Gm3NsYqz9K6asRSRIwd5OVszYbw
Content-Type: application/json

{
	"name": "Gaming Laptops",
	"description": "High-performance gaming laptops",
	"parentCategoryId": "6a510919a0f00edab39f1f0l"
}

### Category - Self Parent Validation

PATCH http://localhost:5000/api/v1/businesses/6a50f1ce20478765e4be70fa/categories/6a5114bea0f00edab39a3f1a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUwZjE4OTIwNDc4NzY1ZTRiZTcwZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MGYxOTUyMDQ3ODc2NWU0YmU3MGY5IiwiaWF0IjoxNzgzNjg5NjIxLCJleHAiOjE3ODM3NzYwMjEsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.081fWblecul08_H5Gm3NsYqz9K6asRSRIwd5OVszYbw
Content-Type: application/json

{
	"parentCategoryId": "6a5114bea0f00edab39a3f1a"
}

### Category - Validation

POST http://localhost:5000/api/v1/businesses/6a50f1ce20478765e4be70fa/categories/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUwZjE4OTIwNDc4NzY1ZTRiZTcwZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MGYxOTUyMDQ3ODc2NWU0YmU3MGY5IiwiaWF0IjoxNzgzNjg5NjIxLCJleHAiOjE3ODM3NzYwMjEsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.081fWblecul08_H5Gm3NsYqz9K6asRSRIwd5OVszYbw
Content-Type: application/json

# {
# 	"description": "Electronic devices and accessories"
# }

# {
# 	"name": "",
# 	"description": "Electronic devices"
# }

{
	"name": "Gaming",
	"parentCategoryId": "abc123"
}

### Inventory - create (POST http://localhost:5000/api/v1/businesses/{{businessId}}/inventory, {"productId": "{{productId}}", "sku": "DX13-001", "quantity": 50, "reservedQuantity": 0, "reorderLevel": 10, "location": "Main Warehouse"})

POST http://localhost:5000/api/v1/businesses/6a5354689c212dd935c84351/inventory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUzNTM0ODljMjEyZGQ5MzVjODQzNGUiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MzUzNTQ5YzIxMmRkOTM1Yzg0MzUwIiwiaWF0IjoxNzgzODQ1NzE2LCJleHAiOjE3ODM5MzIxMTYsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ._LeoV30JfOg5Q9RM-QspWVOCXI3LGKVq_A4lA4hQpog
Content-Type: application/json

{
	"productId": "6a5354d49c212dd935c84354",
	"quantity": 50,
	"reservedQuantity": 0,
	"lowStockThreshold": 20
}

# # Test 3 — Duplicate Inventory

# {
# 	"productId": "6a5273efa46baa0222c36a7a",
# 	"quantity": 25,
# 	"reservedQuantity": 0,
# 	"lowStockThreshold": 6
# }

### Inventory - read

GET http://localhost:5000/api/v1/businesses/6a5265b409bfdeb110fd5f9a/inventory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUwZjE4OTIwNDc4NzY1ZTRiZTcwZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MjY1OTQwOWJmZGViMTEwZmQ1Zjk5IiwiaWF0IjoxNzgzNzg0ODUyLCJleHAiOjE3ODM4NzEyNTIsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.Qsu4zZ-HqcGOfrDIyGxtejbDrZy345-A1kT4IOt0Ib8

### Inventory - read 1

GET http://localhost:5000/api/v1/businesses/6a5354689c212dd935c84351/inventory/6a53559f9c212dd935c84356
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUzNTM0ODljMjEyZGQ5MzVjODQzNGUiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MzUzNTQ5YzIxMmRkOTM1Yzg0MzUwIiwiaWF0IjoxNzgzODQ1NzE2LCJleHAiOjE3ODM5MzIxMTYsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ._LeoV30JfOg5Q9RM-QspWVOCXI3LGKVq_A4lA4hQpog

### Inventory - update

PATCH http://localhost:5000/api/v1/businesses/6a5265b409bfdeb110fd5f9a/inventory/6a527de0b4c64266f264f671
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUwZjE4OTIwNDc4NzY1ZTRiZTcwZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MjY1OTQwOWJmZGViMTEwZmQ1Zjk5IiwiaWF0IjoxNzgzNzg0ODUyLCJleHAiOjE3ODM4NzEyNTIsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.Qsu4zZ-HqcGOfrDIyGxtejbDrZy345-A1kT4IOt0Ib8
Content-Type: application/json

{
	"quantity": 70, 
	"lowStockThreshold": 10
}

### Inventory - delete

DELETE http://localhost:5000/api/v1/businesses/6a5265b409bfdeb110fd5f9a/inventory/6a527de0b4c64266f264f671
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUwZjE4OTIwNDc4NzY1ZTRiZTcwZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MjY1OTQwOWJmZGViMTEwZmQ1Zjk5IiwiaWF0IjoxNzgzNzg0ODUyLCJleHAiOjE3ODM4NzEyNTIsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.Qsu4zZ-HqcGOfrDIyGxtejbDrZy345-A1kT4IOt0Ib8

### Inventory - restore

PATCH http://localhost:5000/api/v1/businesses/6a5265b409bfdeb110fd5f9a/inventory/6a527de0b4c64266f264f671/restore
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUwZjE4OTIwNDc4NzY1ZTRiZTcwZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MjY1OTQwOWJmZGViMTEwZmQ1Zjk5IiwiaWF0IjoxNzgzNzg0ODUyLCJleHAiOjE3ODM4NzEyNTIsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.Qsu4zZ-HqcGOfrDIyGxtejbDrZy345-A1kT4IOt0Ib8

### Inventory - Reserved Quantity Validation

PATCH http://localhost:5000/api/v1/businesses/6a5265b409bfdeb110fd5f9a/inventory/6a527de0b4c64266f264f671
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUwZjE4OTIwNDc4NzY1ZTRiZTcwZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MjY1OTQwOWJmZGViMTEwZmQ1Zjk5IiwiaWF0IjoxNzgzNzg0ODUyLCJleHAiOjE3ODM4NzEyNTIsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.Qsu4zZ-HqcGOfrDIyGxtejbDrZy345-A1kT4IOt0Ib8
Content-Type: application/json

{
	"quantity": 10,
	"reservedQuantity": 15
}

### Inventory - Validation

POST http://localhost:5000/api/v1/businesses/6a5265b409bfdeb110fd5f9a/inventory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUwZjE4OTIwNDc4NzY1ZTRiZTcwZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MjY1OTQwOWJmZGViMTEwZmQ1Zjk5IiwiaWF0IjoxNzgzNzg0ODUyLCJleHAiOjE3ODM4NzEyNTIsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.Qsu4zZ-HqcGOfrDIyGxtejbDrZy345-A1kT4IOt0Ib8
Content-Type: application/json

{
	"quantity": -5,
	"reservedQuantity": -1
}

### Stock Movement - create stock in movement (POST http://localhost:5000/api/v1/businesses/{{businessId}}/stock-movements, {"inventoryId": "{{inventoryId}}", "type": "STOCK_IN", "quantity": 20, "reason": "Supplier delivery", "notes": "Purchase Order #PO-1001"}). This should:
	### - create a StockMovement document
	### - increase inventory quantity
	### - create an Audit Log

POST http://localhost:5000/api/v1/businesses/6a5354689c212dd935c84351/stock-movements
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUzNTM0ODljMjEyZGQ5MzVjODQzNGUiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MzUzNTQ5YzIxMmRkOTM1Yzg0MzUwIiwiaWF0IjoxNzgzODQ1NzE2LCJleHAiOjE3ODM5MzIxMTYsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ._LeoV30JfOg5Q9RM-QspWVOCXI3LGKVq_A4lA4hQpog
Content-Type: application/json

{
    "inventoryId": "6a53559f9c212dd935c84356",
    "type": "STOCK_IN",
    "quantity": 20,
    "reason": "Supplier delivery",
    "notes": "Purchase Order #PO-1001"
}

# GET http://localhost:5000/api/v1/businesses/6a5265b409bfdeb110fd5f9a/stock-movements
# Authorization: Bearer YOUR_ACCESS_TOKEN

### Stock Movement - read

GET http://localhost:5000/api/v1/businesses/6a5354689c212dd935c84351/stock-movements
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUzNTM0ODljMjEyZGQ5MzVjODQzNGUiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MzUzNTQ5YzIxMmRkOTM1Yzg0MzUwIiwiaWF0IjoxNzgzODQ1NzE2LCJleHAiOjE3ODM5MzIxMTYsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ._LeoV30JfOg5Q9RM-QspWVOCXI3LGKVq_A4lA4hQpog

### Stock Movement - read 1

GET http://localhost:5000/api/v1/businesses/6a5354689c212dd935c84351/stock-movements/6a53593bead45f56f759afa8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUzNTM0ODljMjEyZGQ5MzVjODQzNGUiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MzUzNTQ5YzIxMmRkOTM1Yzg0MzUwIiwiaWF0IjoxNzgzODQ1NzE2LCJleHAiOjE3ODM5MzIxMTYsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ._LeoV30JfOg5Q9RM-QspWVOCXI3LGKVq_A4lA4hQpog

### Stock Movement - create stock out movement

POST http://localhost:5000/api/v1/businesses/6a5354689c212dd935c84351/stock-movements
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUzNTM0ODljMjEyZGQ5MzVjODQzNGUiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MzUzNTQ5YzIxMmRkOTM1Yzg0MzUwIiwiaWF0IjoxNzgzODQ1NzE2LCJleHAiOjE3ODM5MzIxMTYsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ._LeoV30JfOg5Q9RM-QspWVOCXI3LGKVq_A4lA4hQpog
Content-Type: application/json

{
    "inventoryId": "6a53559f9c212dd935c84356",
    "type": "STOCK_OUT",
    "quantity": 10,
    "reason": "Customer purchase",
    "notes": "Invoice INV-1004"
}

### Stock Movement - stock adjustment (+/-) ({"inventoryId": "6a53559f9c212dd935c84356", "type": "ADJUSTMENT", "quantity": -3, "reason": "Damaged items", "notes": "Warehouse inspection"})

POST http://localhost:5000/api/v1/businesses/6a5354689c212dd935c84351/stock-movements
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUzNTM0ODljMjEyZGQ5MzVjODQzNGUiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MzUzNTQ5YzIxMmRkOTM1Yzg0MzUwIiwiaWF0IjoxNzgzODQ1NzE2LCJleHAiOjE3ODM5MzIxMTYsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ._LeoV30JfOg5Q9RM-QspWVOCXI3LGKVq_A4lA4hQpog
Content-Type: application/json

{
    "inventoryId": "6a53559f9c212dd935c84356",
    "type": "ADJUSTMENT",
    "quantity": 5,
    "reason": "Stock recount",
    "notes": "Found extra units"
}

# {
#     "inventoryId": "6a53559f9c212dd935c84356",
#     "type": "ADJUSTMENT",
#     "quantity": -3,
#     "reason": "Damaged items",
#     "notes": "Warehouse inspection"
# }


### Stock Movement - Negative Inventory

POST http://localhost:5000/api/v1/businesses/6a5354689c212dd935c84351/stock-movements
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUzNTM0ODljMjEyZGQ5MzVjODQzNGUiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MzUzNTQ5YzIxMmRkOTM1Yzg0MzUwIiwiaWF0IjoxNzgzODQ1NzE2LCJleHAiOjE3ODM5MzIxMTYsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ._LeoV30JfOg5Q9RM-QspWVOCXI3LGKVq_A4lA4hQpog
Content-Type: application/json

{
    "inventoryId": "6a53559f9c212dd935c84356",
    "type": "STOCK_OUT",
    "quantity": 9999,
    "reason": "Invalid test",
    "notes": "Should fail"
}

# {}

### Stock Movement - Pagination

GET http://localhost:5000/api/v1/businesses/6a5354689c212dd935c84351/stock-movements?page=1&limit=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTUzNTM0ODljMjEyZGQ5MzVjODQzNGUiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MzUzNTQ5YzIxMmRkOTM1Yzg0MzUwIiwiaWF0IjoxNzgzODQ1NzE2LCJleHAiOjE3ODM5MzIxMTYsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ._LeoV30JfOg5Q9RM-QspWVOCXI3LGKVq_A4lA4hQpog

### Product Image - create ({"productId": "6a549e57f904ed96377f22fd", "url": "https://res.cloudinary.com/demo/image/upload/v1234567890/products/dell-xps-13-front.jpg", "storageKey": "products/dell-xps-13-front", "altText": "Dell XPS 13 Front View", "isPrimary": true, "sortOrder": 1})

POST http://localhost:5000/api/v1/businesses/6a549e05f904ed96377f22fa/product-images
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTU0OWQ4N2Y5MDRlZDk2Mzc3ZjIyZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1NDlkOTFmOTA0ZWQ5NjM3N2YyMmY5IiwiaWF0IjoxNzgzOTMwMjU3LCJleHAiOjE3ODQwMTY2NTcsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.uO0x-74xtobxCBGfcmwasznziGkTFJQwXmdAMNf-rYg
Content-Type: application/json

# {
# 	"productId": "6a54aaf055340597b1648ffb",
# 	"url": "https://res.cloudinary.com/demo/image/upload/v1234567890/products/dell-xps-13-front.jpg",
# 	"storageKey": "products/dell-xps-13-front",
# 	"altText": "Dell XPS 13 Front View",
# 	"isPrimary": true,
# 	"sortOrder": 1
# }

# {
# 	"productId": "6a54aaf055340597b1648ffb",
# 	"url": "https://res.cloudinary.com/demo/image/upload/v1234567890/products/dell-xps-13-back.jpg",
# 	"storageKey": "products/dell-xps-13-back",
# 	"altText": "Dell XPS 13 Rear View",
# 	"sortOrder": 2
# }

# (invalid productId)

# {
# 	"productId": "688888888888888888888888",
# 	"url": "https://example.com/image.jpg",
# 	"storageKey": "products/example",
# 	"altText": "Invalid Product"
# }

{}

###

### Upload Product Image

POST http://localhost:5000/api/v1/businesses/6a549e05f904ed96377f22fa/product-images
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTU0OWQ4N2Y5MDRlZDk2Mzc3ZjIyZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1NWYxZDk1MDNkYWI2ZGNkY2U1ZTJkIiwiaWF0IjoxNzg0MDE3MzY5LCJleHAiOjE3ODQxMDM3NjksImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ZSLunSfIixzO9Git6Pl_6xp-FguswZsNTtSR_tp1jaA
Content-Type: multipart/form-data; boundary=ProductImageBoundary

--ProductImageBoundary
Content-Disposition: form-data; name="productId"

6a54aaf055340597b1648ffb
--ProductImageBoundary
Content-Disposition: form-data; name="altText"

Dell XPS 13 Front View
--ProductImageBoundary
Content-Disposition: form-data; name="isPrimary"

true
--ProductImageBoundary
Content-Disposition: form-data; name="sortOrder"

1
--ProductImageBoundary
Content-Disposition: form-data; name="image"; filename="dell-front.jpg"
Content-Type: image/txt

# < ../../../../../assets/pictures/Screenshot 2026-04-15 023840.png
# --ProductImageBoundary--

< ../../../../../assets/pictures/6mb.txt
--ProductImageBoundary--

### Product Image - read

GET http://localhost:5000/api/v1/businesses/6a549e05f904ed96377f22fa/product-images
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTU0OWQ4N2Y5MDRlZDk2Mzc3ZjIyZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1NWYxZDk1MDNkYWI2ZGNkY2U1ZTJkIiwiaWF0IjoxNzg0MDE3MzY5LCJleHAiOjE3ODQxMDM3NjksImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ZSLunSfIixzO9Git6Pl_6xp-FguswZsNTtSR_tp1jaA

### Product Image - read (invalid business)

GET http://localhost:5000/api/v1/businesses/688888888888888888888888/product-images
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTU0OWQ4N2Y5MDRlZDk2Mzc3ZjIyZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1NDlkOTFmOTA0ZWQ5NjM3N2YyMmY5IiwiaWF0IjoxNzgzOTMwMjU3LCJleHAiOjE3ODQwMTY2NTcsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.uO0x-74xtobxCBGfcmwasznziGkTFJQwXmdAMNf-rYg

### Product Image - read 1

GET http://localhost:5000/api/v1/businesses/6a549e05f904ed96377f22fa/product-images/6a55e528a514d1b8a2d607ed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTU0OWQ4N2Y5MDRlZDk2Mzc3ZjIyZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1NDlkOTFmOTA0ZWQ5NjM3N2YyMmY5IiwiaWF0IjoxNzgzOTMwMjU3LCJleHAiOjE3ODQwMTY2NTcsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.uO0x-74xtobxCBGfcmwasznziGkTFJQwXmdAMNf-rYg

### ### Product Image - read 1 (GET http://localhost:5000/api/v1/businesses/6a549e05f904ed96377f22fa/product-images/688888888888888888888888)

GET http://localhost:5000/api/v1/businesses/6a549e05f904ed96377f22fa/product-images/688888888888888888888888
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTU0OWQ4N2Y5MDRlZDk2Mzc3ZjIyZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1NDlkOTFmOTA0ZWQ5NjM3N2YyMmY5IiwiaWF0IjoxNzgzOTMwMjU3LCJleHAiOjE3ODQwMTY2NTcsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.uO0x-74xtobxCBGfcmwasznziGkTFJQwXmdAMNf-rYg

### Product Image - update

PATCH http://localhost:5000/api/v1/businesses/6a549e05f904ed96377f22fa/product-images/6a54ab8b55340597b1648fff
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTU0OWQ4N2Y5MDRlZDk2Mzc3ZjIyZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1NDlkOTFmOTA0ZWQ5NjM3N2YyMmY5IiwiaWF0IjoxNzgzOTMwMjU3LCJleHAiOjE3ODQwMTY2NTcsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.uO0x-74xtobxCBGfcmwasznziGkTFJQwXmdAMNf-rYg
Content-Type: application/json

{
	"altText": "Updated Dell XPS 13 Front View",
	"sortOrder": 5
}

### Product Image - set primary (PATCH http://localhost:5000/api/v1/businesses/6a549e05f904ed96377f22fa/product-images/:imageId/primary)

PATCH http://localhost:5000/api/v1/businesses/6a549e05f904ed96377f22fa/product-images/6a54ab8b55340597b1648fff/primary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTU0OWQ4N2Y5MDRlZDk2Mzc3ZjIyZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1NDlkOTFmOTA0ZWQ5NjM3N2YyMmY5IiwiaWF0IjoxNzgzOTMwMjU3LCJleHAiOjE3ODQwMTY2NTcsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.uO0x-74xtobxCBGfcmwasznziGkTFJQwXmdAMNf-rYg

### Product Image - delete

DELETE http://localhost:5000/api/v1/businesses/6a549e05f904ed96377f22fa/product-images/6a55f658503dab6dcdce5e33
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTU0OWQ4N2Y5MDRlZDk2Mzc3ZjIyZjciLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1NWYxZDk1MDNkYWI2ZGNkY2U1ZTJkIiwiaWF0IjoxNzg0MDE3MzY5LCJleHAiOjE3ODQxMDM3NjksImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ZSLunSfIixzO9Git6Pl_6xp-FguswZsNTtSR_tp1jaA

### Product Price - create

POST http://localhost:5000/api/v1/businesses/6a567237b716e970fcb22872/product-prices
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTU2NzE2YmI3MTZlOTcwZmNiMjI4NmYiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1NjcxZjBiNzE2ZTk3MGZjYjIyODcxIiwiaWF0IjoxNzg0MDUwMTYxLCJleHAiOjE3ODQxMzY1NjEsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.nBouUTAcgh800KSmXygq7pxULUhCFuL5UMlLSEx7HBU
Content-Type: application/json

# {
#     "productId": "6a567298b716e970fcb22875",
#     "sellingPrice": 189999,
#     "costPrice": 165000,
#     "currency": "KES",
#     "changeReason": "Initial product pricing"
# }

# {
#     "productId": "6a567298b716e970fcb22875",
#     "sellingPrice": 199999,
#     "costPrice": 195000,
#     "currency": "KES",
#     "changeReason": "Supply cost increased."
# }

# Invalid Product

{
    "productId": "688888888888888888888888",
    "sellingPrice": 199999,
    "costPrice": 195000,
    "currency": "KES",
    "changeReason": "Supply cost increased."
}

### Product Price - read 1

GET http://localhost:5000/api/v1/businesses/6a567237b716e970fcb22872/product-prices
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTU2NzE2YmI3MTZlOTcwZmNiMjI4NmYiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1NjcxZjBiNzE2ZTk3MGZjYjIyODcxIiwiaWF0IjoxNzg0MDUwMTYxLCJleHAiOjE3ODQxMzY1NjEsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.nBouUTAcgh800KSmXygq7pxULUhCFuL5UMlLSEx7HBU

### Product Price - filter

GET http://localhost:5000/api/v1/businesses/6a567237b716e970fcb22872/product-prices?isCurrent=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTU2NzE2YmI3MTZlOTcwZmNiMjI4NmYiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1NjcxZjBiNzE2ZTk3MGZjYjIyODcxIiwiaWF0IjoxNzg0MDUwMTYxLCJleHAiOjE3ODQxMzY1NjEsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.nBouUTAcgh800KSmXygq7pxULUhCFuL5UMlLSEx7HBU

### Product Price

POST http://localhost:5000/api/v1/businesses/6a567237b716e970fcb22872/product-prices
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTU2NzE2YmI3MTZlOTcwZmNiMjI4NmYiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1NjcxZjBiNzE2ZTk3MGZjYjIyODcxIiwiaWF0IjoxNzg0MDUwMTYxLCJleHAiOjE3ODQxMzY1NjEsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.nBouUTAcgh800KSmXygq7pxULUhCFuL5UMlLSEx7HBU
Content-Type: application/json

{
    "productId": "6a567298b716e970fcb22875",
    "sellingPrice": 199999.95,
    "costPrice": 150500.75,
    "currency": "KES",
    "changeReason": "Precision test"
}