### Create a new product (POST http://localhost:5000/api/v1/businesses/:businessId/products)

POST http://localhost:5000/api/v1/businesses/6a567237b716e970fcb22872/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTU2NzE2YmI3MTZlOTcwZmNiMjI4NmYiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1NjcxZjBiNzE2ZTk3MGZjYjIyODcxIiwiaWF0IjoxNzg0MDUwMTYxLCJleHAiOjE3ODQxMzY1NjEsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.nBouUTAcgh800KSmXygq7pxULUhCFuL5UMlLSEx7HBU
Content-Type: application/json

{
  "name": "Dell XPS 13",
  "shortDescription": "Premium ultrabook",
  "description": "Intel Core Ultra, 16GB RAM, 512GB SSD",
  "sku": "DX13-001"
}

### List products (POST http://localhost:5000/api/v1/businesses/:businessId/products)

GET http://localhost:5000/api/v1/businesses/6a504c77e7296c01375cc578/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTRiOWQ4ODBiZTRkNDU1ZjRlNjhlNTAiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MDRiZDZlNzI5NmMwMTM3NWNjNTc3IiwiaWF0IjoxNzgzNjQ3MTkwLCJleHAiOjE3ODM3MzM1OTAsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ljIk-GFI1NZO5YAuZHYkLX56IHvjxAJbN5eNzOxqpSY
Content-Type: application/json

### get product data

GET http://localhost:5000/api/v1/businesses/6a504c77e7296c01375cc578/products/6a504e01e7296c01375cc57d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTRiOWQ4ODBiZTRkNDU1ZjRlNjhlNTAiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MDRiZDZlNzI5NmMwMTM3NWNjNTc3IiwiaWF0IjoxNzgzNjQ3MTkwLCJleHAiOjE3ODM3MzM1OTAsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ljIk-GFI1NZO5YAuZHYkLX56IHvjxAJbN5eNzOxqpSY
Content-Type: application/json

### Update product data

PATCH http://localhost:5000/api/v1/businesses/6a504c77e7296c01375cc578/products/6a504e01e7296c01375cc57d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTRiOWQ4ODBiZTRkNDU1ZjRlNjhlNTAiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MDRiZDZlNzI5NmMwMTM3NWNjNTc3IiwiaWF0IjoxNzgzNjQ3MTkwLCJleHAiOjE3ODM3MzM1OTAsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ljIk-GFI1NZO5YAuZHYkLX56IHvjxAJbN5eNzOxqpSY
Content-Type: application/json

{
  "name": "Dell XPS 13 Plus",
  "sku": "DX13-010"
}

### Delete product data

DELETE http://localhost:5000/api/v1/businesses/6a504c77e7296c01375cc578/products/6a504e01e7296c01375cc57d/restore
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTRiOWQ4ODBiZTRkNDU1ZjRlNjhlNTAiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MDRiZDZlNzI5NmMwMTM3NWNjNTc3IiwiaWF0IjoxNzgzNjQ3MTkwLCJleHAiOjE3ODM3MzM1OTAsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ljIk-GFI1NZO5YAuZHYkLX56IHvjxAJbN5eNzOxqpSY
Content-Type: application/json

### Delete product data

PATCH http://localhost:5000/api/v1/businesses/6a504c77e7296c01375cc578/products/6a504e01e7296c01375cc57d/restore
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTRiOWQ4ODBiZTRkNDU1ZjRlNjhlNTAiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE1MDRiZDZlNzI5NmMwMTM3NWNjNTc3IiwiaWF0IjoxNzgzNjQ3MTkwLCJleHAiOjE3ODM3MzM1OTAsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ljIk-GFI1NZO5YAuZHYkLX56IHvjxAJbN5eNzOxqpSY
Content-Type: application/json