### Archive Offering

PATCH http://localhost:5000/api/v1/businesses/6a6c7a15c4217e5be0e7c210/offerings/6a70b4a6a44b5abec1b7f9b7/archive
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTY4Nzc3Yzg2MTRjM2Y4Mzg3ZjVkYzgiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE3MDQ4OTE2ZjgyMGU0NDM5MjU2ODE2IiwiaWF0IjoxNzg1NzQzNTA1LCJleHAiOjE3ODU4Mjk5MDUsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ZQB769uLMKV7oWBKlrMk8314pj26OaMUa881AM0VO4Q

### Restore Offering

PATCH http://localhost:5000/api/v1/businesses/6a6c7a15c4217e5be0e7c210/offerings/6a70b4a6a44b5abec1b7f9b7/restore
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTY4Nzc3Yzg2MTRjM2Y4Mzg3ZjVkYzgiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE3MDQ4OTE2ZjgyMGU0NDM5MjU2ODE2IiwiaWF0IjoxNzg1NzQzNTA1LCJleHAiOjE3ODU4Mjk5MDUsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ZQB769uLMKV7oWBKlrMk8314pj26OaMUa881AM0VO4Q

### Filter by type

GET http://localhost:5000/api/v1/businesses/6a6c7a15c4217e5be0e7c210/offerings?type=PRODUCT
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTY4Nzc3Yzg2MTRjM2Y4Mzg3ZjVkYzgiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE3MDQ4OTE2ZjgyMGU0NDM5MjU2ODE2IiwiaWF0IjoxNzg1NzQzNTA1LCJleHAiOjE3ODU4Mjk5MDUsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ZQB769uLMKV7oWBKlrMk8314pj26OaMUa881AM0VO4Q

### Filter by status

GET http://localhost:5000/api/v1/businesses/6a6c7a15c4217e5be0e7c210/offerings?status=ACTIVE
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTY4Nzc3Yzg2MTRjM2Y4Mzg3ZjVkYzgiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE3MDQ4OTE2ZjgyMGU0NDM5MjU2ODE2IiwiaWF0IjoxNzg1NzQzNTA1LCJleHAiOjE3ODU4Mjk5MDUsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ZQB769uLMKV7oWBKlrMk8314pj26OaMUa881AM0VO4Q

### Filter by visibility

GET http://localhost:5000/api/v1/businesses/6a6c7a15c4217e5be0e7c210/offerings?visibility=PUBLIC
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTY4Nzc3Yzg2MTRjM2Y4Mzg3ZjVkYzgiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE3MDQ4OTE2ZjgyMGU0NDM5MjU2ODE2IiwiaWF0IjoxNzg1NzQzNTA1LCJleHAiOjE3ODU4Mjk5MDUsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ZQB769uLMKV7oWBKlrMk8314pj26OaMUa881AM0VO4Q

### Search

GET http://localhost:5000/api/v1/businesses/6a6c7a15c4217e5be0e7c210/offerings?search=hotel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTY4Nzc3Yzg2MTRjM2Y4Mzg3ZjVkYzgiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE3MDQ4OTE2ZjgyMGU0NDM5MjU2ODE2IiwiaWF0IjoxNzg1NzQzNTA1LCJleHAiOjE3ODU4Mjk5MDUsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.ZQB769uLMKV7oWBKlrMk8314pj26OaMUa881AM0VO4Q
