@baseUrl = http://localhost:5000/api/v1
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YThkZGVlMzRjNjhhYzc0NWZkZTk3ZGMiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE5ZmE5Yjc4ZWQ3YzVkNDc5YjA0YzNhIiwiaWF0IjoxNzg4ODQ4NTY3LCJleHAiOjE3ODg5MzQ5NjcsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.RWglcgq3X8tdt_Af2bOnB1oV-XRsVEP0AaTpmmQeD0c
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YThkZGVlMzRjNjhhYzc0NWZkZTk3ZGMiLCJqdGkiOiIyMGI3YzVjOC1lNTcyLTQ2ZTAtOGE2Yy04ZWRlY2E2NmRkMzgiLCJpYXQiOjE3ODg4NDk0MDcsImV4cCI6MTc5MDA1OTAwNywiYXVkIjoidGFzc2lhcWNhLWNsaWVudCIsImlzcyI6InRhc3NpYXFjYSJ9.a-ImPewLlNENm9Tu-mqBq7KVpag2BI4tqYqZoEJt2Uw

@email = designsolutions1629@gmail.com

@password = keith@1234

### Register - user A

POST {{baseUrl}}/auth/register
Content-Type: application/json

# {
#     "firstName": "Keith",
#     "lastName": "Owino",
#     "email": "designsolutions1629@gmail.com",
#     "phone": "+254768290857",
#     "password": "keith@1234"
# }

# # User B

{
    "firstName": "Love",
    "lastName": "Rembo",
    "email": "rembo1234@gmail.com",
    "phone": "+254734567890",
    "password": "rembo@1234"
}

# # User C

# {
#     "firstName": "Maurine",
#     "lastName": "Ougo",
#     "email": "maurine1234@gmail.com",
#     "phone": "+254734567890",
#     "password": "maurine@1234"
# }

# # User D

# {
#     "firstName": "Lee",
#     "lastName": "Chen",
#     "email": "lee1234@gmail.com",
#     "phone": "+254734567890",
#     "password": "lee@1234"
# }

### Register Invalid email

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "firstName": "Love",
    "lastName": "Rembo",
    "email": "rembo1234",
    "phone": "+254734567890",
    "password": "rembo@1234"
}

### Register with weak password

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "firstName": "Love",
    "lastName": "Rembo",
    "email": "rembo1234@gmail.com",
    "phone": "+254734567890",
    "password": "1234"
}

### Register missing first name

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "firstName": "",
    "lastName": "Rembo",
    "email": "rembo1234@gmail.com",
    "phone": "+254734567890",
    "password": "rembo@1234"
}

### Invalid request

POST {{baseUrl}}/auth/register
Content-Type: application/json

{}

### Login

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### Successful Refresh ("refreshToken": "<refresh_token_from_login_response>"), then Reuse the Old Refresh Token

POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

### Authentication — Valid Access Token (First, log in then copy the returned access token.)

GET {{baseUrl}}/auth/me
Authorization: Bearer {{accessToken}}

### Logout ("refreshToken": "{{refreshToken}}")

POST {{baseUrl}}/auth/logout
Content-Type: application/json

{
	"refreshToken": "{{refreshToken}}"
}

### sessions

GET {{baseUrl}}/auth/sessions
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### revoke/ delete 1 of User A's sessions

DELETE {{baseUrl}}/auth/sessions/6a9ead2ead9ee3879986245c
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### Revoke other User A's sessions

DELETE {{baseUrl}}/auth/sessions
Authorization: Bearer {{accessToken}}
Content-Type: application/json