const AUDIT_ACTIONS = {
	/**
	 * Business
	 */
	BUSINESS_CREATED: "BUSINESS_CREATED",
	BUSINESS_UPDATED: "BUSINESS_UPDATED",

	/**
	 * Members
	 */
	MEMBER_INVITED: "MEMBER_INVITED",
	MEMBER_REMOVED: "MEMBER_REMOVED",
	MEMBER_ROLE_CHANGED: "MEMBER_ROLE_CHANGED",
	MEMBER_DEACTIVATED: "MEMBER_DEACTIVATED",
	MEMBER_REACTIVATED: "MEMBER_REACTIVATED",
	MEMBER_LEFT: "MEMBER_LEFT",
	OWNERSHIP_TRANSFERRED: "OWNERSHIP_TRANSFERRED",

	/**
	 * Branches
	 */
	BRANCH_CREATED: "BRANCH_CREATED",
	BRANCH_UPDATED: "BRANCH_UPDATED",
	BRANCH_DEACTIVATED: "BRANCH_DEACTIVATED",
	BRANCH_REACTIVATED: "BRANCH_REACTIVATED",
	HEAD_OFFICE_CHANGED: "HEAD_OFFICE_CHANGED",

	/**
	 * Branch Assignments
	 */
	BRANCH_MEMBER_ASSIGNED: "BRANCH_MEMBER_ASSIGNED",
	BRANCH_MEMBER_UNASSIGNED: "BRANCH_MEMBER_UNASSIGNED",
	BRANCH_MEMBER_REACTIVATED: "BRANCH_MEMBER_REACTIVATED",
	PRIMARY_BRANCH_CHANGED: "PRIMARY_BRANCH_CHANGED",

	/**
	 * Offerings
	 */
	OFFERING_CREATED: "OFFERING_CREATED",
	OFFERING_UPDATED: "OFFERING_UPDATED",
	OFFERING_ARCHIVED: "OFFERING_ARCHIVED",
	OFFERING_RESTORED: "OFFERING_RESTORED",

	/**
	 * Offerings Variant
	 */
	OFFERING_VARIANT_CREATED: "OFFERING_VARIANT_CREATED",
	OFFERING_VARIANT_UPDATED: "OFFERING_VARIANT_UPDATED",
	OFFERING_VARIANT_ARCHIVED: "OFFERING_VARIANT_ARCHIVED",
	OFFERING_VARIANT_RESTORED: "OFFERING_VARIANT_RESTORED",

	/**
	 * Offerings duration
	 */
	OFFERING_DURATION_CREATED: "OFFERING_DURATION_CREATED",
	OFFERING_DURATION_UPDATED: "OFFERING_DURATION_UPDATED",
	OFFERING_DURATION_ARCHIVED: "OFFERING_DURATION_ARCHIVED",
	OFFERING_DURATION_RESTORED: "OFFERING_DURATION_RESTORED",

	/**
	 * Offerings media
	 */
	OFFERING_MEDIA_CREATED: "OFFERING_MEDIA_CREATED",

	/**
	 * Offerings categories
	 */
	OFFERING_CATEGORIES_CREATED: "OFFERING_CATEGORIES_CREATED",

	/**
	 * Offerings pricing
	 */
	OFFERING_PRICING_CREATED: "OFFERING_PRICING_CREATED",

	/**
	 * Offerings seo
	 */
	OFFERING_SEO_CREATED: "OFFERING_SEO_CREATED",
	OFFERING_SEO_UPDATED: "OFFERING_SEO_UPDATED",

	/**
	 * Offerings capacity
	 */
	OFFERING_CAPACITY_CREATED: "OFFERING_CAPACITY_CREATED",
	OFFERING_CAPACITY_UPDATED: "OFFERING_CAPACITY_UPDATED",

	/**
	 * Offerings location
	 */
	OFFERING_LOCATION_CREATED: "OFFERING_LOCATION_CREATED",
	OFFERING_LOCATION_UPDATED: "OFFERING_LOCATION_UPDATED",

	/**
	 * Offerings calendar
	 */
	OFFERING_CALENDAR_CREATED: "OFFERING_CALENDAR_CREATED",
	OFFERING_CALENDAR_UPDATED: "OFFERING_CALENDAR_UPDATED",

	/**
	 * Offerings scheduling
	 */
	OFFERING_SCHEDULING_CREATED: "OFFERING_SCHEDULING_CREATED",
	OFFERING_SCHEDULING_UPDATED: "OFFERING_SCHEDULING_UPDATED",

	/**
	 * Offerings booking
	 */
	OFFERING_BOOKING_CREATED: "OFFERING_BOOKING_CREATED",
	OFFERING_BOOKING_UPDATED: "OFFERING_BOOKING_UPDATED",

	/**
	 * Offerings registration
	 */
	OFFERING_REGISTRATION_CREATED: "OFFERING_REGISTRATION_CREATED",
	OFFERING_REGISTRATION_UPDATED: "OFFERING_REGISTRATION_UPDATED",

	/**
	 * Offerings enrollment
	 */
	OFFERING_ENROLLMENT_CREATED: "OFFERING_ENROLLMENT_CREATED",
	OFFERING_ENROLLMENT_UPDATED: "OFFERING_ENROLLMENT_UPDATED",

	/**
	 * Offerings instructor
	 */
	OFFERING_INSTRUCTOR_ASSIGNED: "OFFERING_INSTRUCTOR_ASSIGNED",

	/**
	 * Offerings membership
	 */
	OFFERING_MEMBERSHIP_CREATED: "OFFERING_MEMBERSHIP_CREATED",
	OFFERING_MEMBERSHIP_UPDATED: "OFFERING_MEMBERSHIP_UPDATED",

	/**
	 * Products
	 */
	PRODUCT_CREATED: "PRODUCT_CREATED",
	PRODUCT_UPDATED: "PRODUCT_UPDATED",
	PRODUCT_ARCHIVED: "PRODUCT_ARCHIVED",
	PRODUCT_RESTORED: "PRODUCT_RESTORED",

	/**
	 * Categories
	 */
	CATEGORY_CREATED: "CATEGORY_CREATED",
	CATEGORY_UPDATED: "CATEGORY_UPDATED",
	CATEGORY_ARCHIVED: "CATEGORY_ARCHIVED",
	CATEGORY_RESTORED: "CATEGORY_RESTORED",

	/**
	 * Inventory
	 */
	INVENTORY_CREATED: "INVENTORY_CREATED",
	INVENTORY_UPDATED: "INVENTORY_UPDATED",
	INVENTORY_ARCHIVED: "INVENTORY_ARCHIVED",
	INVENTORY_RESTORED: "INVENTORY_RESTORED",

	/**
	 * Stock Movement Inventory
	 */
	STOCK_MOVEMENT_CREATE: "STOCK_MOVEMENT_CREATE",

	/**
	 * Product Image
	 */
	PRODUCT_IMAGE_CREATED: "PRODUCT_IMAGE_CREATED",
	PRODUCT_IMAGE_UPDATED: "PRODUCT_IMAGE_UPDATED",
	PRODUCT_IMAGE_DELETED: "PRODUCT_IMAGE_DELETED",
	PRODUCT_IMAGE_ARCHIVED: "PRODUCT_IMAGE_ARCHIVED",
	PRODUCT_IMAGE_RESTORED: "PRODUCT_IMAGE_RESTORED",
	PRODUCT_IMAGE_SET_PRIMARY: "PRODUCT_IMAGE_SET_PRIMARY",
};

export default AUDIT_ACTIONS;
