const AUDIT_ENTITY_TYPES = Object.freeze({
	BUSINESS: "BUSINESS",
	BUSINESS_MEMBER: "BUSINESS_MEMBER",

	BRANCH: "BRANCH",
	BRANCH_ASSIGNMENT: "BRANCH_ASSIGNMENT",

	OFFERING: "OFFERING",
	PRODUCT: "PRODUCT",
	CATEGORY: "CATEGORY",
	INVENTORY: "INVENTORY",
	STOCK_MOVEMENT: "STOCK_MOVEMENT",
	PRODUCT_IMAGE: "PRODUCT_IMAGE",
	PRODUCT_PRICE: "PRODUCT_PRICE",
	PRODUCT_VARIANT: "PRODUCT_VARIANT",

	SERVICE: "SERVICE",

	ORDER: "ORDER",
	PAYMENT: "PAYMENT",

	REVIEW: "REVIEW",
});

export default AUDIT_ENTITY_TYPES;
