const AUDIT_ENTITY_TYPES = Object.freeze({
	BUSINESS: "BUSINESS",
	BUSINESS_MEMBER: "BUSINESS_MEMBER",

	BRANCH: "BRANCH",
	BRANCH_ASSIGNMENT: "BRANCH_ASSIGNMENT",

	OFFERING: "OFFERING",
	OFFERING_VARIANT: "OFFERING_VARIANT",
	OFFERING_DURATION: "OFFERING_DURATION",
	OFFERING_ATTRIBUTES: "OFFERING_ATTRIBUTES",
	OFFERING_MEDIA: "OFFERING_MEDIA",
	OFFERING_CATEGORIES: "OFFERING_CATEGORIES",
	OFFERING_PRICING: "OFFERING_PRICING",
	OFFERING_SEO: "OFFERING_SEO",
	OFFERING_CAPACITY: "OFFERING_CAPACITY",
	OFFERING_LOCATION: "OFFERING_LOCATION",
	OFFERING_CALENDAR: "OFFERING_CALENDAR",

	PRODUCT: "PRODUCT",
	CATEGORY: "CATEGORY",
	INVENTORY: "INVENTORY",
	STOCK_MOVEMENT: "STOCK_MOVEMENT",
	PRODUCT_IMAGE: "PRODUCT_IMAGE",
	PRODUCT_PRICE: "PRODUCT_PRICE",

	SERVICE: "SERVICE",

	ORDER: "ORDER",
	PAYMENT: "PAYMENT",

	REVIEW: "REVIEW",
});

export default AUDIT_ENTITY_TYPES;
