const AUDIT_ACTIONS = {
	/**
	 * Business
	 */
	BUSINESS_CREATED: "BUSINESS_CREATED",
	BUSINESS_UPDATED: "BUSINESS_UPDATED",

	/**
	 * Members
	 */
	MEMBER_INVITED: "MEMBER_INVITED",
	MEMBER_REMOVED: "MEMBER_REMOVED",
	MEMBER_ROLE_CHANGED: "MEMBER_ROLE_CHANGED",
	MEMBER_DEACTIVATED: "MEMBER_DEACTIVATED",
	MEMBER_REACTIVATED: "MEMBER_REACTIVATED",
	MEMBER_LEFT: "MEMBER_LEFT",
	OWNERSHIP_TRANSFERRED: "OWNERSHIP_TRANSFERRED",

	/**
	 * Branches
	 */
	BRANCH_CREATED: "BRANCH_CREATED",
	BRANCH_UPDATED: "BRANCH_UPDATED",
	BRANCH_DEACTIVATED: "BRANCH_DEACTIVATED",
	BRANCH_REACTIVATED: "BRANCH_REACTIVATED",
	HEAD_OFFICE_CHANGED: "HEAD_OFFICE_CHANGED",

	/**
	 * Branch Assignments
	 */
	BRANCH_MEMBER_ASSIGNED: "BRANCH_MEMBER_ASSIGNED",
	BRANCH_MEMBER_UNASSIGNED: "BRANCH_MEMBER_UNASSIGNED",
	BRANCH_MEMBER_REACTIVATED: "BRANCH_MEMBER_REACTIVATED",
	PRIMARY_BRANCH_CHANGED: "PRIMARY_BRANCH_CHANGED",

	/**
	 * Offerings
	 */
	OFFERING_CREATED: "OFFERING_CREATED",
	OFFERING_UPDATED: "OFFERING_UPDATED",
	OFFERING_ARCHIVED: "OFFERING_ARCHIVED",
	OFFERING_RESTORED: "OFFERING_RESTORED",

	/**
	 * Offerings Variant
	 */
	OFFERING_VARIANT_CREATED: "OFFERING_VARIANT_CREATED",
	OFFERING_VARIANT_UPDATED: "OFFERING_VARIANT_UPDATED",
	OFFERING_VARIANT_ARCHIVED: "OFFERING_VARIANT_ARCHIVED",
	OFFERING_VARIANT_RESTORED: "OFFERING_VARIANT_RESTORED",

	/**
	 * Products
	 */
	PRODUCT_CREATED: "PRODUCT_CREATED",
	PRODUCT_UPDATED: "PRODUCT_UPDATED",
	PRODUCT_ARCHIVED: "PRODUCT_ARCHIVED",
	PRODUCT_RESTORED: "PRODUCT_RESTORED",

	/**
	 * Categories
	 */
	CATEGORY_CREATED: "CATEGORY_CREATED",
	CATEGORY_UPDATED: "CATEGORY_UPDATED",
	CATEGORY_ARCHIVED: "CATEGORY_ARCHIVED",
	CATEGORY_RESTORED: "CATEGORY_RESTORED",

	/**
	 * Inventory
	 */
	INVENTORY_CREATED: "INVENTORY_CREATED",
	INVENTORY_UPDATED: "INVENTORY_UPDATED",
	INVENTORY_ARCHIVED: "INVENTORY_ARCHIVED",
	INVENTORY_RESTORED: "INVENTORY_RESTORED",

	/**
	 * Stock Movement Inventory
	 */
	STOCK_MOVEMENT_CREATE: "STOCK_MOVEMENT_CREATE",

	/**
	 * Product Image
	 */
	PRODUCT_IMAGE_CREATED: "PRODUCT_IMAGE_CREATED",
	PRODUCT_IMAGE_UPDATED: "PRODUCT_IMAGE_UPDATED",
	PRODUCT_IMAGE_DELETED: "PRODUCT_IMAGE_DELETED",
	PRODUCT_IMAGE_ARCHIVED: "PRODUCT_IMAGE_ARCHIVED",
	PRODUCT_IMAGE_RESTORED: "PRODUCT_IMAGE_RESTORED",
	PRODUCT_IMAGE_SET_PRIMARY: "PRODUCT_IMAGE_SET_PRIMARY",

	/**
	 * Product Price
	 */
	PRODUCT_PRICE_CREATED: "PRODUCT_PRICE_CREATED",
};

export default AUDIT_ACTIONS;
