export const OFFERING_TYPES = {
	PRODUCT: "PRODUCT",
	SERVICE: "SERVICE",
	MEAL: "MEAL",
	RENTAL: "RENTAL",
	DIGITAL: "DIGITAL",
	BOOKING: "BOOKING",
	SUBSCRIPTION: "SUBSCRIPTION",
	PACKAGE: "PACKAGE",
};
