export const OFFERING_SUBSCRIPTION_BILLING_INTERVAL_UNITS = Object.freeze({
	DAY: "DAY",
	WEEK: "WEEK",
	MONTH: "MONTH",
	YEAR: "YEAR",
});

export const OFFERING_SUBSCRIPTION_BILLING_INTERVAL_UNIT_VALUES = Object.freeze(
	Object.values(OFFERING_SUBSCRIPTION_BILLING_INTERVAL_UNITS),
);
