const Permissions = {
	// Business
	BUSINESS_CREATE: "BUSINESS_CREATE",
	BUSINESS_UPDATE: "BUSINESS_UPDATE",
	BUSINESS_DELETE: "BUSINESS_DELETE",
	BUSINESS_TRANSFER_OWNERSHIP: "BUSINESS_TRANSFER_OWNERSHIP",

	AUDIT_LOG_VIEW: "AUDIT_LOG_VIEW",

	// Business member
	MEMBER_INVITE: "MEMBER_INVITE",
	MEMBER_VIEW: "MEMBER_VIEW",
	MEMBER_ROLE_UPDATE: "MEMBER_ROLE_UPDATE",
	MEMBER_REMOVE: "MEMBER_REMOVE",

	// Branch
	BRANCH_CREATE: "BRANCH_CREATE",
	BRANCH_VIEW: "BRANCH_VIEW",
	BRANCH_UPDATE: "BRANCH_UPDATE",
	BRANCH_DEACTIVATE: "BRANCH_DEACTIVATE",
	BRANCH_REACTIVATE: "BRANCH_REACTIVATE",
	BRANCH_MEMBER_ASSIGN: "BRANCH_MEMBER_ASSIGN",
	BRANCH_MEMBER_VIEW: "BRANCH_MEMBER_VIEW",
	BRANCH_MEMBER_REMOVE: "BRANCH_MEMBER_REMOVE",

	// Category
	CATEGORY_VIEW: "CATEGORY_VIEW",
	CATEGORY_CREATE: "CATEGORY_CREATE",
	CATEGORY_UPDATE: "CATEGORY_UPDATE",
	CATEGORY_DELETE: "CATEGORY_DELETE",

	// Offering
	OFFERING_VIEW: "OFFERING_VIEW",
	OFFERING_CREATE: "OFFERING_CREATE",
	OFFERING_UPDATE: "OFFERING_UPDATE",
	OFFERING_ARCHIVE: "OFFERING_ARCHIVE",
	OFFERING_RESTORE: "OFFERING_RESTORE",

	// Product
	PRODUCT_CREATE: "PRODUCT_CREATE",
	PRODUCT_VIEW: "PRODUCT_VIEW",
	PRODUCT_UPDATE: "PRODUCT_UPDATE",
	PRODUCT_DELETE: "PRODUCT_DELETE",

	// Inventory
	INVENTORY_VIEW: "INVENTORY_VIEW",
	INVENTORY_CREATE: "INVENTORY_CREATE",
	INVENTORY_UPDATE: "INVENTORY_UPDATE",
	INVENTORY_DELETE: "INVENTORY_DELETE",

	// Stock Movement
	STOCK_MOVEMENT_CREATE: "STOCK_MOVEMENT_CREATE",
	STOCK_MOVEMENT_VIEW: "STOCK_MOVEMENT_VIEW",
	STOCK_MOVEMENT_EXPORT: "STOCK_MOVEMENT_EXPORT",

	// Product Image
	PRODUCT_IMAGE_CREATE: "PRODUCT_IMAGE_CREATE",
	PRODUCT_IMAGE_VIEW: "PRODUCT_IMAGE_VIEW",
	PRODUCT_IMAGE_UPDATE: "PRODUCT_IMAGE_UPDATE",
	PRODUCT_IMAGE_DELETE: "PRODUCT_IMAGE_DELETE",
	// PRODUCT_IMAGE_SET_PRIMARY: "PRODUCT_IMAGE_SET_PRIMARY",

	// Product Price
	PRODUCT_PRICE_CREATE: "PRODUCT_PRICE_CREATE",
	PRODUCT_PRICE_VIEW: "PRODUCT_PRICE_VIEW",

	// Product Variant
	PRODUCT_VARIANT_VIEW: "PRODUCT_VARIANT_VIEW",
	PRODUCT_VARIANT_CREATE: "PRODUCT_VARIANT_CREATE",
	PRODUCT_VARIANT_UPDATE: "PRODUCT_VARIANT_UPDATE",
	PRODUCT_VARIANT_DELETE: "PRODUCT_VARIANT_DELETE",
	PRODUCT_VARIANT_ARCHIVE: "PRODUCT_VARIANT_ARCHIVE",
	PRODUCT_VARIANT_RESTORE: "PRODUCT_VARIANT_RESTORE",

	// Service
	SERVICE_CREATE: "SERVICE_CREATE",
	SERVICE_UPDATE: "SERVICE_UPDATE",
	SERVICE_DELETE: "SERVICE_DELETE",

	REVIEW_REPLY: "REVIEW_REPLY",
};

export default Permissions;
