@baseUrl = http://localhost:5000/api/v1

###
# ! For a category to be returned it has to be _ACTIVE_, it has to have at least one associated _ACTIVE_, _PUBLIC_ and a searchable: true offering.

GET {{baseUrl}}/marketplace/categories
Accept: application/json

###

GET {{baseUrl}}/marketplace/categories?search=Accessories
Accept: application/json

### Category - Business Filter

GET {{baseUrl}}/marketplace/categories?businessId=6a9017d39104fee22462410a
Accept: application/json

###
# ? This message was attached to this endpoint: Important: your current Zod schema does not accept "null" as a special value; parentId is currently just a non-empty string. Therefore, do not run this test yet unless the intended API contract explicitly supports parentId=null.

GET {{baseUrl}}/marketplace/categories?parentId=null
Accept: application/json

###

GET {{baseUrl}}/marketplace/categories?parentId=6a958e496878bfe4f74cc494
Accept: application/json

###

GET {{baseUrl}}/marketplace/categories?page=1&limit=1
Accept: application/json

###

GET {{baseUrl}}/marketplace/categories?businessId=6a9017d39104fee22462410a&search=Accessories
Accept: application/json