### Get offering attributes

GET http://localhost:5000/api/v1/businesses/6a72d57f8b94e4f1232d4112/offerings/6a7ef51c7591965d44febf83/attributes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTcyZDU1YThiOTRlNGYxMjMyZDQxMTAiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE4MDI2NjJkODNmNzkxZTA2ODUyZDVjIiwiaWF0IjoxNzg2NzgzMzMxLCJleHAiOjE3ODY4Njk3MzEsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.Gxr0DS9wBPTzowFJDjuTxsxrclPK8TltWmQ6BCVqnB0
Content-Type: application/json

### Set offering attributes

PUT http://localhost:5000/api/v1/businesses/6a72d57f8b94e4f1232d4112/offerings/6a7ef51c7591965d44febf83/attributes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTcyZDU1YThiOTRlNGYxMjMyZDQxMTAiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE4MDI2NjJkODNmNzkxZTA2ODUyZDVjIiwiaWF0IjoxNzg2NzgzMzMxLCJleHAiOjE3ODY4Njk3MzEsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.Gxr0DS9wBPTzowFJDjuTxsxrclPK8TltWmQ6BCVqnB0
Content-Type: application/json

# {
# 	"attributes": [
# 		{
# 			"name": "Color",
# 			"values": [
# 				"Black",
# 				"White",
# 				"Blue"
# 			]
# 		},
# 		{
# 			"name": "Size",
# 			"values": [
# 				"Small",
# 				"Medium",
# 				"Large"
# 			]
# 		}
# 	]
# }

# {
# 	"attributes": [
# 		{
# 			"name": "Material",
# 			"values": [
# 				"Leather",
# 				"Cotton"
# 			]
# 		},
# 		{
# 			"name": "Pattern",
# 			"values": [
# 				"Plain",
# 				"Striped"
# 			]
# 		}
# 	]
# }

{
	"attributes": [
		{
			"name": "Color",
			"values": [
				"Black",
				"black",
				" BLACK ",
				"White",
				"white"
			]
		}
	]
}

# {
# 	"attributes": [
# 		{
# 			"name": "Color",
# 			"values": [
# 				"Black",
# 				"White"
# 			]
# 		},
# 		{
# 			"name": "color",
# 			"values": [
# 				"Red",
# 				"Blue"
# 			]
# 		}
# 	]
# }