### Duration - Create

POST http://localhost:5000/api/v1/businesses/6a72d57f8b94e4f1232d4112/offerings/6a89442166f866f6ab3126fc/duration
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTcyZDU1YThiOTRlNGYxMjMyZDQxMTAiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE4OTQyOGU2NmY4NjZmNmFiMzEyNmZiIiwiaWF0IjoxNzg3MzgwMzY2LCJleHAiOjE3ODc0NjY3NjYsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.jqh_XgKXJPGu4gpvIiVkrmyx4sGStXzJDuFLltlPdmE
Content-Type: application/json

{
    "duration": 12,
    "unit": "WEEKS"
}

### Duration - Read

GET http://localhost:5000/api/v1/businesses/6a72d57f8b94e4f1232d4112/offerings/6a87d48ee8f335d02db5c88e/duration
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTcyZDU1YThiOTRlNGYxMjMyZDQxMTAiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE4NmI5OGZkZTk3MzhiOTdlZmY4N2JhIiwiaWF0IjoxNzg3MjE0MjIzLCJleHAiOjE3ODczMDA2MjMsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.bSz2Thi92K-gX-HQcT7nvVsIg3sK8-fwzrmif9kFzfA

### Duration - Update

PATCH http://localhost:5000/api/v1/businesses/6a72d57f8b94e4f1232d4112/offerings/6a87d48ee8f335d02db5c88e/duration
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTcyZDU1YThiOTRlNGYxMjMyZDQxMTAiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE4NmI5OGZkZTk3MzhiOTdlZmY4N2JhIiwiaWF0IjoxNzg3MjE0MjIzLCJleHAiOjE3ODczMDA2MjMsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.bSz2Thi92K-gX-HQcT7nvVsIg3sK8-fwzrmif9kFzfA
Content-Type: application/json

{
    "unit": "INVALID"
}

### Duration - Archive

PATCH http://localhost:5000/api/v1/businesses/6a72d57f8b94e4f1232d4112/offerings/6a87d48ee8f335d02db5c88e/duration/archive
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTcyZDU1YThiOTRlNGYxMjMyZDQxMTAiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE4NmI5OGZkZTk3MzhiOTdlZmY4N2JhIiwiaWF0IjoxNzg3MjE0MjIzLCJleHAiOjE3ODczMDA2MjMsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.bSz2Thi92K-gX-HQcT7nvVsIg3sK8-fwzrmif9kFzfA

### Duration - Restore

PATCH http://localhost:5000/api/v1/businesses/6a72d57f8b94e4f1232d4112/offerings/6a87d48ee8f335d02db5c88e/duration/restore
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTcyZDU1YThiOTRlNGYxMjMyZDQxMTAiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uczE2MjlAZ21haWwuY29tIiwic2lkIjoiNmE4NmI5OGZkZTk3MzhiOTdlZmY4N2JhIiwiaWF0IjoxNzg3MjE0MjIzLCJleHAiOjE3ODczMDA2MjMsImF1ZCI6InRhc3NpYXFjYS1jbGllbnQiLCJpc3MiOiJ0YXNzaWFxY2EifQ.bSz2Thi92K-gX-HQcT7nvVsIg3sK8-fwzrmif9kFzfA
