@baseUrl = http://localhost:5000/api/v1

### Business Discovery

GET {{baseUrl}}/marketplace/discovery/businesses
Accept: application/json

### Business Discovery — Explicit Pagination

GET {{baseUrl}}/marketplace/discovery/businesses?page=1&limit=5
Accept: application/json

### Business Discovery — Business Search

GET {{baseUrl}}/marketplace/discovery/businesses?search=Rabbituza
Accept: application/json

### Business Discovery — Search With Pagination

GET {{baseUrl}}/marketplace/discovery/businesses?search=Rabbituza&page=1&limit=1
Accept: application/json

### Business Discovery — Type Filter

GET {{baseUrl}}/marketplace/discovery/businesses?businessType=RETAIL
Accept: application/json

### Business Discovery — Type + Search

GET {{baseUrl}}/marketplace/discovery/businesses?businessType=AGRICULTURE&search=Rabbituza
Accept: application/json

