### Invalid request

POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{}

### Register

POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "firstName": "Love",
    "lastName": "Rembo",
    "email": "rembo1234@gmail.com",
    "phone": "+254734567890",
    "password": "rembo@1234"
}

### Register Invalid email

POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "firstName": "Love",
    "lastName": "Rembo",
    "email": "rembo1234",
    "phone": "+254734567890",
    "password": "rembo@1234"
}

### Register with weak password

POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "firstName": "Love",
    "lastName": "Rembo",
    "email": "rembo1234@gmail.com",
    "phone": "+254734567890",
    "password": "1234"
}

### Register missing first name

POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "firstName": "",
    "lastName": "Rembo",
    "email": "rembo1234@gmail.com",
    "phone": "+254734567890",
    "password": "rembo@1234"
}

### Login

POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "rembo1234@gmail.com",
    "password": "rembo@1234"
}

### Login wrong password

POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "rembo1234@gmail.com",
    "password": "rembo@123"
}

### Login non-existing email

POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "rembo1235@gmail.com",
    "password": "rembo@1234"
}

### Successful Refresh, then Reuse the Old Refresh Token

POST http://localhost:5000/api/v1/auth/refresh
Content-Type: application/json

{
    "refreshToken": "<refresh_token_from_login_response>"
}

### Invalid Refresh Request

POST http://localhost:5000/api/v1/auth/refresh
Content-Type: application/json

{}

### Completely Invalid Token

POST http://localhost:5000/api/v1/auth/refresh
Content-Type: application/json

{
    "refreshToken": "this-is-not-a-jwt"
}

### Authenticateion — No Authorization Header

GET http://localhost:5000/api/v1/auth/me

### Authenticateion — Invalid Access Token

GET http://localhost:5000/api/v1/auth/me
Authorization: Bearer this-is-not-a-token

### Authenticateion — Valid Access Token (First, log in then copy the returned access token.)

GET http://localhost:5000/api/v1/auth/me
Authorization: Bearer this-is-not-a-token